/*

Source Server         : stormscaleDedic
Source Server Version : 50558
Source Host           : localhost:3306
Source Database       : developerworld

Target Server Type    : MYSQL
Target Server Version : 50558
File Encoding         : 65001

Date: 2017-11-28 20:33:55
*/
SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `locales_achievement_reward`
-- ----------------------------
DROP TABLE IF EXISTS `locales_achievement_reward`;
CREATE TABLE `locales_achievement_reward` (
  `entry` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `subject_loc1` varchar(100) NOT NULL DEFAULT '',
  `subject_loc2` varchar(100) NOT NULL DEFAULT '',
  `subject_loc3` varchar(100) NOT NULL DEFAULT '',
  `subject_loc4` varchar(100) NOT NULL DEFAULT '',
  `subject_loc5` varchar(100) NOT NULL DEFAULT '',
  `subject_loc6` varchar(100) NOT NULL DEFAULT '',
  `subject_loc7` varchar(100) NOT NULL DEFAULT '',
  `subject_loc8` varchar(100) NOT NULL DEFAULT '',
  `text_loc1` text,
  `text_loc2` text,
  `text_loc3` text,
  `text_loc4` text,
  `text_loc5` text,
  `text_loc6` text,
  `text_loc7` text,
  `text_loc8` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of locales_achievement_reward
-- ----------------------------
INSERT INTO `locales_achievement_reward` VALUES ('13', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('45', '', 'Vous avez bien bourlinguÃƒÆ’Ã‚Â© !', '', '', '', '', '', '', null, 'Eh ben, vousÃƒâ€šÃ‚Â !\r\n\r\nEt moi qui croyais avoir tout vu sur ces terres gelÃƒÆ’Ã‚Â©esÃƒâ€šÃ‚Â ! Le feu de l\'exploration brÃƒÆ’Ã‚Â»le en vous. Cela saute ÃƒÆ’Ã‚Â  mes yeux de nain.\r\n\r\nPortez ce tabard avec fiertÃƒÆ’Ã‚Â©. De cette faÃƒÆ’Ã‚Â§on, vos amis sauront toujours ÃƒÆ’Ã‚Â  qui demander leur chemin en temps vouluÃƒâ€šÃ‚Â !\r\n\r\nRestez bien en selleÃƒâ€šÃ‚Â !\r\n\r\nBrann Barbe-de-bronze', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('46', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('230', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('456', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('614', '', 'Pour l\'Alliance !', '', '', '', '', '', '', null, 'La guerre fait rage sur nos terres. Seuls les hÃƒÆ’Ã‚Â©ros les plus courageux osent frapper la Horde en ses points les plus sensibles. Vous ÃƒÆ’Ã‚Âªtes l\'un d\'eux.\r\n\r\nLes coups que vous avez portÃƒÆ’Ã‚Â©s au commandement de la Horde vont nous permettre de lancer notre assaut final. La Horde flÃƒÆ’Ã‚Â©chira sous la puissance de l\'Alliance.\r\n\r\nVos actes seront rÃƒÆ’Ã‚Â©compensÃƒÆ’Ã‚Â©s. Chevauchez avec fiertÃƒÆ’Ã‚Â©Ãƒâ€šÃ‚Â !\r\n\r\nÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â Votre roi', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('619', '', 'Pour la Horde !', '', '', '', '', '', '', null, 'En ces temps troublÃƒÆ’Ã‚Â©s, nos souffrances engendrent de vrais hÃƒÆ’Ã‚Â©ros. Vous ÃƒÆ’Ã‚Âªtes l\'un d\'eux. Nous sommes en guerre. Vos efforts soutiennent notre cause en Azeroth. Vos hautes actions seront rÃƒÆ’Ã‚Â©compensÃƒÆ’Ã‚Â©es. Prenez ce prix d\'Orgrimmar et chevauchez vers la gloire. Pour la HordeÃƒâ€šÃ‚Â ! Chef de guerre Thrall', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('714', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('762', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('870', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('871', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('876', '', 'Je vous surveille , enfent.', '', '', '', '', '', '', null, 'Vous avez tout ÃƒÆ’Ã‚Â  fait un don pour vous jeter dans cette arÃƒÆ’Ã‚Â¨ne. Conservez le et. Portez-le avec fiertÃƒÆ’Ã‚Â©. Maintenant retourner lÃƒÆ’Ã‚Â -bas et montrer leur comment c\'est arrivÃƒÆ’Ã‚Â©! $B$B Oncle Sal', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('907', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('913', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('942', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('943', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('945', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('948', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('953', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('978', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1015', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1021', '', 'Bonheur au Haut-Faiteur', '', '', '', '', '', '', null, 'Je ne pouvais pas m\'empÃƒÆ’Ã‚Âªcher de remarquer que c\'est une belle collection de Tabards que vous avez rÃƒÆ’Ã‚Â©ussi ÃƒÆ’Ã‚Â  collecter au fil des saisons. Vous pourriez tout aussi bien ajouter celui-ci ÃƒÆ’Ã‚Â  votre collection. Il est ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© simplement dans la poussiÃƒÆ’Ã‚Â¨re de ma garde-robe.', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1038', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1039', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1174', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1175', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1250', '', 'Nouvelle maison du puant', '', '', '', '', '', '', null, 'J\'ai entendu la faÃƒÆ’Ã‚Â§on dont vous avez pris soin de nos amis ÃƒÆ’Ã‚Â  fourrure. J\'espÃƒÆ’Ã‚Â¨re que vous ne me dÃƒÆ’Ã‚Â©range pas, mais il faut que je prenne une nouvelle maison pour le puant. Il refuse tout simplement de le jouer gentil avec les autres.\r\n\r\n$B$B\r\n\r\nS\'il vous plaÃƒÆ’Ã‚Â®t assurez-vous de lui donner ÃƒÆ’Ã‚Â  manger deux fois par jour. Et euh il a un truc pour les chats noirs.\r\n\r\n$B$B - Breanni', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1400', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1402', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1516', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1563', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1656', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1657', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1658', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1681', '', 'Salutations de Darnassus', '', '', '', '', '', '', null, 'Vos rÃƒÆ’Ã‚Â©alisations ont ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© profondes et de grande envergure. Azeroth, avec l\'ensemble de la rÃƒÆ’Ã‚Â©cente tourmente, bÃƒÆ’Ã‚Â©nÃƒÆ’Ã‚Â©ficie grandement de ceux qui cherchent ÃƒÆ’Ã‚Â  dÃƒÆ’Ã‚Â©barrasser la terre du mal.\r\n\r\n$B$B\r\n\r\nSeuls ceux qui prennent le temps de connaÃƒÆ’Ã‚Â®tre nos terres comprennent les sacrifices de ceux qui sont tombÃƒÆ’Ã‚Â©s et aussi la vaillance de nos hÃƒÆ’Ã‚Â©ros. Vous ÃƒÆ’Ã‚Âªtes tellement un hÃƒÆ’Ã‚Â©ros . J\'espÃƒÆ’Ã‚Â¨re que vous allez racontÃƒÆ’Ã‚Â© les contes de vos aventures pour les annÃƒÆ’Ã‚Â©es ÃƒÆ’Ã‚Â  venir.\r\n\r\n$B$B\r\n\r\nAu nom de l\'Alliance, je vous remercie, MaÃƒÆ’Ã‚Â®tre du Savoir.', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1682', '', 'Salutations de Pitons du Tonnerre', '', '', '', '', '', '', null, 'Les nouvelles de vos rÃƒÆ’Ã‚Â©alisations ont beaucoup voyagÃƒÆ’Ã‚Â©. Le vents hurlent de turbulences sur nos terres. Ceux qui se dressent contre le mal sont notre seul espoir.\r\n\r\n$B$B\r\n\r\nSeuls ceux qui ÃƒÆ’Ã‚Â©coutent les vents comprennent les dettes de nos hÃƒÆ’Ã‚Â©ros tombÃƒÆ’Ã‚Â©s au combat ont payÃƒÆ’Ã‚Â©s pour protÃƒÆ’Ã‚Â©ger notre peuple. Peut un hÃƒÆ’Ã‚Â©ros tel que vous vivre longtemps ÃƒÆ’Ã‚Â  raconter les histoires de de votre aventures. Pour seulement alors que nous rappeler ÃƒÆ’Ã‚Â  quel point nous devons ÃƒÆ’Ã‚Âªtre reconnaissants.\r\n\r\n$B$B\r\n\r\nNotre gratitude est profonde, MaÃƒÆ’Ã‚Â®tre du Savoir.\r\n\r\n$B$B\r\n\r\nPour la Horde!\r\n\r\n$B$B\r\n\r\nCairne Sabot', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1683', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1684', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1691', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1692', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1693', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1707', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1784', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1793', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('1956', '', 'Lectures studieuses', '', '', '', '', '', '', null, 'FÃƒÆ’Ã‚Â©licitationsÃƒâ€šÃ‚Â ! Vous avez terminÃƒÆ’Ã‚Â© d\'ÃƒÆ’Ã‚Â©tudier Ãƒâ€šÃ‚Â«Ãƒâ€šÃ‚Â Les ÃƒÆ’Ã‚Â©coles de magie des arcanesÃƒâ€šÃ‚Â Ãƒâ€šÃ‚Â». En rÃƒÆ’Ã‚Â©compense de votre dÃƒÆ’Ã‚Â©vouement, veuillez trouver ci-joint le volume spÃƒÆ’Ã‚Â©cial qui termine la collection.\r\n\r\nJe pense que vous trouverez ce tome particuliÃƒÆ’Ã‚Â¨rement divertissant. Mais je vous laisse le dÃƒÆ’Ã‚Â©couvrir par vous-mÃƒÆ’Ã‚Âªme.\r\n\r\nCordialement,\r\n\r\nRhonin', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2051', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2054', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2096', '', 'Le MaÃƒÆ’Ã‚Â®tre des piÃƒÆ’Ã‚Â¨ces', '', '', '', '', '', '', null, 'Salutations et fÃƒÆ’Ã‚Â©licitations pour la collecte de l\'ensemble des piÃƒÆ’Ã‚Â¨ces de monnaie de Dalaran! En tant que votre rÃƒÆ’Ã‚Â©compense pour tout votre travail dur, j\'ai joint un un tout nouvel Sceau de titane de Dalaran. Il s\'agit d\'une piÃƒÆ’Ã‚Â¨ce de monnaie spÃƒÆ’Ã‚Â©ciale que nous n\'avons laccorder qu\'aux plus ardent des collectionneurs.\r\n\r\n$B$B\r\n\r\nJ\'espÃƒÆ’Ã‚Â¨re que vous apprÃƒÆ’Ã‚Â©cierez cette rÃƒÆ’Ã‚Â©compense spÃƒÆ’Ã‚Â©ciale. Vous l\'avez bien mÃƒÆ’Ã‚Â©ritÃƒÆ’Ã‚Â©!\r\n\r\n$B$B\r\n\r\nCordialement,\r\n\r\n$B\r\n\r\nJepetto JoyBuzz Le MaÃƒÆ’Ã‚Â®tre des piÃƒÆ’Ã‚Â¨ces', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2136', '', 'Gloire au hÃƒÆ’Ã‚Â©ros', '', '', '', '', '', '', null, 'Champion,\r\n\r\n$B$B\r\n\r\nLes mots ce sont rendu aux Temple du Repos du ver que de grandes actions hÃƒÆ’Ã‚Â©roÃƒÆ’Ã‚Â¯ques que vous avez atteints depuis votre arrivÃƒÆ’Ã‚Â©e en Norfendre.\r\n\r\n$B$B\r\n\r\nVotre bravoure ne devrait pas passer inaperÃƒÆ’Ã‚Â§u. S\'il vous plaÃƒÆ’Ã‚Â®t accepter ce don au nom des aspects. Ensemble, nous allon nous dÃƒÆ’Ã‚Â©barrasser du mal en Azeroth, une fois et pour l\'ÃƒÆ’Ã‚Â©ternitÃƒÆ’Ã‚Â©.\r\n\r\n$B$B\r\n\r\nAlexstrasza la Lieuse de vie', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2143', '', 'Diriger la cavalerie', '', '', '', '', '', '', null, 'Je ne pouvais pas m\'empÃƒÆ’Ã‚Âªcher de remarquer combien vous ÃƒÆ’Ã‚Âªtes bon avec le bÃƒÆ’Ã‚Â©tail. Avec toute l\'activitÃƒÆ’Ã‚Â© autour d\'ici, les affaires ont ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© mieux que jamais pour moi. Je ne pense pas que vous auriez a l\'esprit de chercher ce Drake Albinos pour moi? Je n\'ai tout simplement pas assez de minutes de rechange dans la journÃƒÆ’Ã‚Â©e pour prendre soin de tous ces animaux. Bien ÃƒÆ’Ã‚Â  vous, Mei', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2144', '', 'Voyages au bout du monde', '', '', '', '', '', '', null, 'Avec les tambours de guerre rÃƒÆ’Ã‚Â©sonnant au loin, il est facile pour les citoyens d\'Azeroth ÃƒÆ’Ã‚Â  oublier tout ce que la vie a ÃƒÆ’Ã‚Â  offrir.\r\n\r\n$B$B\r\n\r\nVous, en revanche, conservÃƒÆ’Ã‚Â© la dignitÃƒÆ’Ã‚Â© des bonnes courses d\'Azeroth avec votre capacitÃƒÆ’Ã‚Â© ÃƒÆ’Ã‚Â  vous rappeler pour ce que nous luttons. Pour ne pas cÃƒÆ’Ã‚Â©lÃƒÆ’Ã‚Â©brer nos victoires cela constitue une autre forme de la dÃƒÆ’Ã‚Â©faite. Souvenez-vous bien ÃƒÆ’Ã‚Â©galement, revÃƒÆ’Ã‚Â©lateur.\r\n\r\n$B$B\r\n\r\nQue les autres soit inspirÃƒÆ’Ã‚Â© par votre bonne humeur,\r\n\r\n$B$B\r\n\r\nAlexstrasza la Lieuse de vie', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2145', '', 'Voyages au bout du monde', '', '', '', '', '', '', null, 'Avec les tambours de guerre rÃƒÆ’Ã‚Â©sonnant au loin, il est facile pour les citoyens d\'Azeroth ÃƒÆ’Ã‚Â  oublier tout ce que la vie a ÃƒÆ’Ã‚Â  offrir.\r\n\r\n$B$B\r\n\r\nVous, en revanche, conservÃƒÆ’Ã‚Â© la dignitÃƒÆ’Ã‚Â© des bonnes courses d\'Azeroth avec votre capacitÃƒÆ’Ã‚Â© ÃƒÆ’Ã‚Â  vous rappeler pour ce que nous luttons. Pour ne pas cÃƒÆ’Ã‚Â©lÃƒÆ’Ã‚Â©brer nos victoires cela constitue une autre forme de la dÃƒÆ’Ã‚Â©faite. Souvenez-vous bien ÃƒÆ’Ã‚Â©galement, revÃƒÆ’Ã‚Â©lateur.\r\n\r\n$B$B\r\n\r\nQue les autres soit inspirÃƒÆ’Ã‚Â© par votre bonne humeur,\r\n\r\n$B$B\r\n\r\nAlexstrasza la Lieuse de vie', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2186', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2187', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2188', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2336', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2516', '', 'La chasse au p\'tit gibier', '', '', '', '', '', '', null, 'Bonjour!\r\n\r\n$B$B\r\n\r\nJe comprends que vous avez rÃƒÆ’Ã‚Â©ussi ÃƒÆ’Ã‚Â  donner a cette espiÃƒÆ’Ã‚Â¨gle un foyer chaleureux et aimant J\'espÃƒÆ’Ã‚Â©rais que vous pourriez envisager d\'en apportÃƒÆ’Ã‚Â© un autre orphelin ÃƒÆ’Ã‚Â©garÃƒÆ’Ã‚Â©?\r\n\r\n$B$B\r\n\r\nCe petit faon est un timide, mais vous n\'aurez aucun mal ÃƒÆ’Ã‚Â  gagner son amitiÃƒÆ’Ã‚Â© avec le clos: son sel prÃƒÆ’Ã‚Â©fÃƒÆ’Ã‚Â©rÃƒÆ’Ã‚Â© a lÃƒÆ’Ã‚Â©cher!\r\n\r\n$B$B\r\n\r\nBreanni', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2536', '', 'Une montagne de montures', '', '', '', '', '', '', null, 'J\'ai entendu vos ÃƒÆ’Ã‚Â©curies sont presque aussi vaste que les mienne, dÃƒÆ’Ã‚Â©sormais. Impressionnant! Peut-ÃƒÆ’Ã‚Âªtre nous pouvons nous aider les uns les autres ..\r\n\r\nJ\'ai un trop grand nombre de faucons-dragons, et espÃƒÆ’Ã‚Â¨re que vous pourriez donner ÃƒÆ’Ã‚Â  ceux-ci une maison. Naturellement ils sont ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© formÃƒÆ’Ã‚Â©s en tant que monture et non pas comme un animal de compagnie de chasse, et vous le trouverez aussi loyal et infatigable que toute autre coursier je vous le dit.\r\n\r\n$B\r\n\r\nVÃƒÆ’Ã‚Â´tres , Mei', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2537', '', 'Une montagne de montures', '', '', '', '', '', '', null, 'J\'ai entendu vos ÃƒÆ’Ã‚Â©curies sont presque aussi vaste que les mienne, dÃƒÆ’Ã‚Â©sormais. Impressionnant! Peut-ÃƒÆ’Ã‚Âªtre nous pouvons nous aider les uns les autres ..\r\n\r\nJ\'ai un trop grand nombre de faucons-dragons, et espÃƒÆ’Ã‚Â¨re que vous pourriez donner ÃƒÆ’Ã‚Â  ceux-ci une maison. Naturellement ils sont ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© formÃƒÆ’Ã‚Â©s en tant que monture et non pas comme un animal de compagnie de chasse, et vous le trouverez aussi loyal et infatigable que toute autre coursier je vous le dit.\r\n\r\n$B\r\n\r\nVÃƒÆ’Ã‚Â´tres , Mei', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2760', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2761', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2762', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2763', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2764', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2765', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2766', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2767', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2768', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2769', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2797', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2798', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2816', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2817', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2903', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2904', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2957', '', 'Gloire ÃƒÆ’Ã‚Â  l\'ÃƒÆ’Ã‚Â©cumeur de raids ', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('2958', '', 'Gloire ÃƒÆ’Ã‚Â  l\'ÃƒÆ’Ã‚Â©cumeur de raids - HÃƒÆ’Ã‚Â©roique', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3036', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3037', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3117', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3259', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3316', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3478', '', 'Un dindon n\'est pas encore gobÃƒÆ’Ã‚Â©', '', '', '', '', '', '', null, 'Pouvez-vous croire, cette Dinde Dodue a survÃƒÆ’Ã‚Â©cu au travers du mois de Novembre?$B$BDepuis tous ses amis ont ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© servis sur des tables garnis de confitures de cerises et farci de pain d\'ÃƒÆ’Ã‚Â©pice et .... euh....Je commence ÃƒÆ’Ã‚Â  avoir faim, Mais de toute faÃƒÆ’Ã‚Â§on!Il est tout seul, maintenant, alors j\'espÃƒÆ’Ã‚Â©rais que vous pourriez accepter de prendre soin de lui. Il n\'y at tout simplement pas assez de place dans ma boutique!$B$BSuffit de le tenir ÃƒÆ’Ã‚Â©loignÃƒÆ’Ã‚Â© des feux de cuisine, s\'il vous plaÃƒÆ’Ã‚Â®t. Il a un de ces regard ÃƒÆ’Ã‚Â©trange quand il ce trouve autour d\'eux ...', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3656', '', 'Un dindon n\'est pas encore gobÃƒÆ’Ã‚Â©', '', '', '', '', '', '', null, 'Pouvez-vous croire, cette Dinde Dodue a survÃƒÆ’Ã‚Â©cu au travers du mois de Novembre?$B$BDepuis tous ses amis ont ÃƒÆ’Ã‚Â©tÃƒÆ’Ã‚Â© servis sur des tables garnis de confitures de cerises et farci de pain d\'ÃƒÆ’Ã‚Â©pice et .... euh....Je commence ÃƒÆ’Ã‚Â  avoir faim, Mais de toute faÃƒÆ’Ã‚Â§on!Il est tout seul, maintenant, alors j\'espÃƒÆ’Ã‚Â©rais que vous pourriez accepter de prendre soin de lui. Il n\'y at tout simplement pas assez de place dans ma boutique!$B$BSuffit de le tenir ÃƒÆ’Ã‚Â©loignÃƒÆ’Ã‚Â© des feux de cuisine, s\'il vous plaÃƒÆ’Ã‚Â®t. Il a un de ces regard ÃƒÆ’Ã‚Â©trange quand il ce trouve autour d\'eux ...', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3857', '', 'MaÃƒÆ’Ã‚Â®tre de l\'ÃƒÆ’Ã‚Â®le des ConquÃƒÆ’Ã‚Â©rants', '', '', '', '', '', '', null, 'Honorable $N ,\r\n\r\n$B$B\r\n\r\nPour vos actions sur l\'ÃƒÆ’Ã‚Â®le des ConquÃƒÆ’Ã‚Â©rants, il est de mon honneur de vous prÃƒÆ’Ã‚Â©senter ce tabard. Portez-le fiÃƒÆ’Ã‚Â¨rement.\r\n\r\n$B$B\r\n\r\nLe haut-commandant, 7e LÃƒÆ’Ã‚Â©gion', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('3957', '', 'MaÃƒÆ’Ã‚Â®tre de l\'ÃƒÆ’Ã‚Â®le des ConquÃƒÆ’Ã‚Â©rants', '', '', '', '', '', '', null, 'Honorable $N,\r\n\r\n$B$B\r\n\r\nFor your deeds upon the Isle of Conquest, it is my honor to present you with this tabard. Wear it proudly.\r\n\r\n$B$B\r\n\r\nOverlord Agmar', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4078', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4079', '', 'Une offrande ÃƒÆ’Ã‚Â  l\'immortalitÃƒÆ’Ã‚Â©', '', '', '', '', '', '', null, 'Cher $N ,\r\n\r\n$B$B\r\n\r\nHistoires de vos rÃƒÆ’Ã‚Â©cente performance dans le Tournoi du grand croisÃƒÆ’Ã‚Â© sera dÃƒÆ’Ã‚Â©clarÃƒÆ’Ã‚Â©, et redit, pour les siÃƒÆ’Ã‚Â¨cles ÃƒÆ’Ã‚Â  venir. Comme la Croisade d\'argent a lancÃƒÆ’Ã‚Â© son appel pour les plus grands champions d\'Azeroth pour tester leur courage dans le creuset du ColisÃƒÆ’Ã‚Â©e, j\' espÃƒÆ’Ã‚Â©rÃƒÆ’Ã‚Â© contre toute espÃƒÆ’Ã‚Â©rance que les marques de la lumiÃƒÆ’Ã‚Â¨re tels que vous et vos compagnons peuvent ressortiront de la bataille.\r\n\r\n$B$B\r\n\r\nNous allons avoir besoin de vous cruellement dans la bataille ÃƒÆ’Ã‚Â  venir contre le roi-liche. Mais en ce jour, se rÃƒÆ’Ã‚Â©jouir et cÃƒÆ’Ã‚Â©lÃƒÆ’Ã‚Â©brer votre accomplissement glorieux et accepter ce don de l\'un de nos chevaux de bataille les plus nobles. Lorsque le FlÃƒÆ’Ã‚Â©au vois son ÃƒÆ’Ã‚Â©tendard qui se profile ÃƒÆ’Ã‚Â  l\'horizon, hÃƒÆ’Ã‚Â©ros, leur fin est proche!\r\n\r\n$B$B\r\n\r\nBien ÃƒÆ’Ã‚Â  vous,\r\n\r\n$B\r\n\r\nTirion Fordring', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4080', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4156', '', 'Une offrande ÃƒÆ’Ã‚Â  l\'immortalitÃƒÆ’Ã‚Â©', '', '', '', '', '', '', null, 'Cher $N ,\r\n\r\n$B$B\r\n\r\nHistoires de vos rÃƒÆ’Ã‚Â©cente performance dans le Tournoi du grand croisÃƒÆ’Ã‚Â© sera dÃƒÆ’Ã‚Â©clarÃƒÆ’Ã‚Â©, et redit, pour les siÃƒÆ’Ã‚Â¨cles ÃƒÆ’Ã‚Â  venir. Comme la Croisade d\'argent a lancÃƒÆ’Ã‚Â© son appel pour les plus grands champions d\'Azeroth pour tester leur courage dans le creuset du ColisÃƒÆ’Ã‚Â©e, j\' espÃƒÆ’Ã‚Â©rÃƒÆ’Ã‚Â© contre toute espÃƒÆ’Ã‚Â©rance que les marques de la lumiÃƒÆ’Ã‚Â¨re tels que vous et vos compagnons peuvent ressortiront de la bataille.\r\n\r\n$B$B\r\n\r\nNous allons avoir besoin de vous cruellement dans la bataille ÃƒÆ’Ã‚Â  venir contre le roi-liche. Mais en ce jour, se rÃƒÆ’Ã‚Â©jouir et cÃƒÆ’Ã‚Â©lÃƒÆ’Ã‚Â©brer votre accomplissement glorieux et accepter ce don de l\'un de nos chevaux de bataille les plus nobles. Lorsque le FlÃƒÆ’Ã‚Â©au vois son ÃƒÆ’Ã‚Â©tendard qui se profile ÃƒÆ’Ã‚Â  l\'horizon, hÃƒÆ’Ã‚Â©ros, leur fin est proche!\r\n\r\n$B$B\r\n\r\nBien ÃƒÆ’Ã‚Â  vous,\r\n\r\n$B\r\n\r\nTirion Fordring', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4477', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4478', '', 'Groupe improvisÃƒÆ’Ã‚Â©', '', '', '', '', '', '', null, '$gCher membre assidu:ChÃƒÆ’Ã‚Â¨re membre assidue;,\r\n\r\nnous aimerions rÃƒÆ’Ã‚Â©compenser votre tÃƒÆ’Ã‚Â©nacitÃƒÆ’Ã‚Â© ÃƒÆ’Ã‚Â  parcourir les donjons avec des personnes que vous n\'aviez probablement jamais rencontrÃƒÆ’Ã‚Â©es auparavant. Vous avez peut-ÃƒÆ’Ã‚Âªtre mÃƒÆ’Ã‚Âªme appris les ficelles du mÃƒÆ’Ã‚Â©tier ÃƒÆ’Ã‚Â  quelques petits nouveaux.\r\n\r\nBref, nous avons entendu dire que vous aimiez les groupes improvisÃƒÆ’Ã‚Â©s. Alors voici le petit Groopy, qui proclamera ÃƒÆ’Ã‚Â  tout le mondeÃƒâ€šÃ‚Â : Ãƒâ€šÃ‚Â«Ãƒâ€šÃ‚Â Vous savez quoiÃƒâ€šÃ‚Â ? J\'suis groupÃƒÆ’Ã‚Â©Ãƒâ€šÃ‚Â !Ãƒâ€šÃ‚Â Ãƒâ€šÃ‚Â»\r\n\r\nAvec toute notre affection,\r\n\r\nVos amis de l\'ÃƒÆ’Ã‚Â©quipe de dÃƒÆ’Ã‚Â©veloppement de WoW', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4530', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4583', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4584', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4597', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4598', '', '', '', '', '', '', '', '', null, null, null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4602', '', 'Gloire ÃƒÆ’Ã‚Â  l\'ÃƒÆ’Ã‚Â©cumeur de raids de la Couronne de glace', '', '', '', '', '', '', null, '$N ,\r\n\r\n$B$B\r\n\r\nAlors que l\'influence du roi-liche s\'affaiblit, certains de ses serviteurs les plus puissants ont arrachÃƒÆ’Ã‚Â© libÃƒÆ’Ã‚Â©rÃƒÆ’Ã‚Â© de son emprise.\r\n\r\n$B$B\r\n\r\nCe wyrm de givre que mes hommes ont capturÃƒÆ’Ã‚Â©s est un parfait exemple. Elle a une volontÃƒÆ’Ã‚Â© d\'elle et plus encore\r\n\r\n$B$B\r\n\r\nUn de mes hommes a perdu un bras en l\'amenant ici , mais elle prend maintenant part aux cavaliers assez bien.\r\n\r\n$B$B\r\n\r\nS\'il vous plaÃƒÆ’Ã‚Â®t accepter cette magnifique bÃƒÆ’Ã‚Âªte comme un don des Chevaliers de la Lame d\'ÃƒÆ’Ã‚Â©bÃƒÆ’Ã‚Â¨ne. C\'ÃƒÆ’Ã‚Â©tait un honneur de combattre ÃƒÆ’Ã‚Â  vos cÃƒÆ’Ã‚Â´tÃƒÆ’Ã‚Â©s dans la plus grande des batailles.\r\n\r\n$B$B\r\n\r\nAvec honneur,\r\n\r\n$B\r\n\r\nGÃƒÆ’Ã‚Â©nÃƒÆ’Ã‚Â©ralissime Darion.', null, null, null, null, null, null);
INSERT INTO `locales_achievement_reward` VALUES ('4603', '', 'Gloire ÃƒÆ’Ã‚Â  l\'ÃƒÆ’Ã‚Â©cumeur de raids de la Couronne de glace', '', '', '', '', '', '', null, '$N ,\r\n\r\n$B$B\r\n\r\nAlors que l\'influence du roi-liche s\'affaiblit, certains de ses serviteurs les plus puissants ont arrachÃƒÆ’Ã‚Â© libÃƒÆ’Ã‚Â©rÃƒÆ’Ã‚Â© de son emprise.\r\n\r\n$B$B\r\n\r\nCe wyrm de givre que mes hommes ont capturÃƒÆ’Ã‚Â©s est un parfait exemple. Elle a une volontÃƒÆ’Ã‚Â© d\'elle et plus encore\r\n\r\n$B$B\r\n\r\nUn de mes hommes a perdu un bras en l\'amenant ici , mais elle prend maintenant part aux cavaliers assez bien.\r\n\r\n$B$B\r\n\r\nS\'il vous plaÃƒÆ’Ã‚Â®t accepter cette magnifique bÃƒÆ’Ã‚Âªte comme un don des Chevaliers de la Lame d\'ÃƒÆ’Ã‚Â©bÃƒÆ’Ã‚Â¨ne. C\'ÃƒÆ’Ã‚Â©tait un honneur de combattre ÃƒÆ’Ã‚Â  vos cÃƒÆ’Ã‚Â´tÃƒÆ’Ã‚Â©s dans la plus grande des batailles.\r\n\r\n$B$B\r\n\r\nAvec honneur,\r\n\r\n$B\r\n\r\nGÃƒÆ’Ã‚Â©nÃƒÆ’Ã‚Â©ralissime Darion.', null, null, null, null, null, null);
